// Generated by npm run db:types from the checked-in migrations using PostgreSQL introspection.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = { public: {
Tables: {
"admin_audit_log": {
Row: {
"id": string;
"actor_id": string | null;
"entity_type": string;
"entity_id": string;
"action": string;
"created_at": string;
};
Insert: {
"id"?: string;
"actor_id"?: string | null;
"entity_type": string;
"entity_id": string;
"action": string;
"created_at"?: string;
};
Update: {
"id"?: string;
"actor_id"?: string | null;
"entity_type"?: string;
"entity_id"?: string;
"action"?: string;
"created_at"?: string;
};
Relationships: [];
};
"cart_items": {
Row: {
"id": string;
"cart_id": string;
"product_id": string;
"variant_id": string | null;
"line_key": string;
"selected_options": Json;
"product_title": string;
"product_slug": string;
"sku": string | null;
"image_path": string | null;
"quantity": number;
"base_unit_amount": number;
"display_unit_amount": number;
"display_currency": string;
"fx_rate_id": string | null;
"priced_at": string;
"is_valid": boolean;
"validation_message": string | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"cart_id": string;
"product_id": string;
"variant_id"?: string | null;
"line_key": string;
"selected_options"?: Json;
"product_title": string;
"product_slug": string;
"sku"?: string | null;
"image_path"?: string | null;
"quantity": number;
"base_unit_amount": number;
"display_unit_amount": number;
"display_currency": string;
"fx_rate_id"?: string | null;
"priced_at"?: string;
"is_valid"?: boolean;
"validation_message"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"cart_id"?: string;
"product_id"?: string;
"variant_id"?: string | null;
"line_key"?: string;
"selected_options"?: Json;
"product_title"?: string;
"product_slug"?: string;
"sku"?: string | null;
"image_path"?: string | null;
"quantity"?: number;
"base_unit_amount"?: number;
"display_unit_amount"?: number;
"display_currency"?: string;
"fx_rate_id"?: string | null;
"priced_at"?: string;
"is_valid"?: boolean;
"validation_message"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [];
};
"carts": {
Row: {
"id": string;
"token_hash": string;
"currency": string;
"destination_country": string;
"expires_at": string;
"created_at": string;
"updated_at": string;
"discount_code": string | null;
};
Insert: {
"id"?: string;
"token_hash": string;
"currency"?: string;
"destination_country"?: string;
"expires_at"?: string;
"created_at"?: string;
"updated_at"?: string;
"discount_code"?: string | null;
};
Update: {
"id"?: string;
"token_hash"?: string;
"currency"?: string;
"destination_country"?: string;
"expires_at"?: string;
"created_at"?: string;
"updated_at"?: string;
"discount_code"?: string | null;
};
Relationships: [];
};
"collections": {
Row: {
"id": string;
"slug": string;
"name": string;
"description": string;
"image_path": string | null;
"image_alt": string;
"active": boolean;
"sort_order": number;
"seo_title": string | null;
"seo_description": string | null;
"created_at": string;
"updated_at": string;
"description_document": Json | null;
"asset_id": string | null;
};
Insert: {
"id"?: string;
"slug": string;
"name": string;
"description"?: string;
"image_path"?: string | null;
"image_alt"?: string;
"active"?: boolean;
"sort_order"?: number;
"seo_title"?: string | null;
"seo_description"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"description_document"?: Json | null;
"asset_id"?: string | null;
};
Update: {
"id"?: string;
"slug"?: string;
"name"?: string;
"description"?: string;
"image_path"?: string | null;
"image_alt"?: string;
"active"?: boolean;
"sort_order"?: number;
"seo_title"?: string | null;
"seo_description"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"description_document"?: Json | null;
"asset_id"?: string | null;
};
Relationships: [];
};
"currency_rates": {
Row: {
"id": string;
"base_currency": string;
"quote_currency": string;
"rate_numerator": number;
"rate_denominator": number;
"source": string;
"source_effective_at": string;
"fetched_at": string;
};
Insert: {
"id"?: string;
"base_currency"?: string;
"quote_currency": string;
"rate_numerator": number;
"rate_denominator": number;
"source": string;
"source_effective_at": string;
"fetched_at"?: string;
};
Update: {
"id"?: string;
"base_currency"?: string;
"quote_currency"?: string;
"rate_numerator"?: number;
"rate_denominator"?: number;
"source"?: string;
"source_effective_at"?: string;
"fetched_at"?: string;
};
Relationships: [];
};
"discount_collections": {
Row: {
"discount_id": string;
"collection_id": string;
};
Insert: {
"discount_id": string;
"collection_id": string;
};
Update: {
"discount_id"?: string;
"collection_id"?: string;
};
Relationships: [];
};
"discount_products": {
Row: {
"discount_id": string;
"product_id": string;
};
Insert: {
"discount_id": string;
"product_id": string;
};
Update: {
"discount_id"?: string;
"product_id"?: string;
};
Relationships: [];
};
"discount_redemptions": {
Row: {
"id": string;
"discount_id": string;
"redemption_key": string;
"email_identity_hash": string;
"phone_identity_hash": string;
"status": "RESERVED" | "REDEEMED" | "RELEASED";
"amount": number;
"currency": string;
"expires_at": string | null;
"redeemed_at": string | null;
"created_at": string;
};
Insert: {
"id"?: string;
"discount_id": string;
"redemption_key": string;
"email_identity_hash": string;
"phone_identity_hash": string;
"status"?: "RESERVED" | "REDEEMED" | "RELEASED";
"amount": number;
"currency": string;
"expires_at"?: string | null;
"redeemed_at"?: string | null;
"created_at"?: string;
};
Update: {
"id"?: string;
"discount_id"?: string;
"redemption_key"?: string;
"email_identity_hash"?: string;
"phone_identity_hash"?: string;
"status"?: "RESERVED" | "REDEEMED" | "RELEASED";
"amount"?: number;
"currency"?: string;
"expires_at"?: string | null;
"redeemed_at"?: string | null;
"created_at"?: string;
};
Relationships: [];
};
"discounts": {
Row: {
"id": string;
"code": string;
"name": string;
"kind": "PERCENTAGE" | "FIXED_AMOUNT";
"percentage_basis_points": number | null;
"fixed_amount": number | null;
"minimum_subtotal": number;
"starts_at": string | null;
"ends_at": string | null;
"active": boolean;
"total_usage_limit": number | null;
"per_customer_limit": number | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"code": string;
"name": string;
"kind": "PERCENTAGE" | "FIXED_AMOUNT";
"percentage_basis_points"?: number | null;
"fixed_amount"?: number | null;
"minimum_subtotal"?: number;
"starts_at"?: string | null;
"ends_at"?: string | null;
"active"?: boolean;
"total_usage_limit"?: number | null;
"per_customer_limit"?: number | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"code"?: string;
"name"?: string;
"kind"?: "PERCENTAGE" | "FIXED_AMOUNT";
"percentage_basis_points"?: number | null;
"fixed_amount"?: number | null;
"minimum_subtotal"?: number;
"starts_at"?: string | null;
"ends_at"?: string | null;
"active"?: boolean;
"total_usage_limit"?: number | null;
"per_customer_limit"?: number | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [];
};
"homepage_collections": {
Row: {
"collection_id": string;
"sort_order": number;
};
Insert: {
"collection_id": string;
"sort_order": number;
};
Update: {
"collection_id"?: string;
"sort_order"?: number;
};
Relationships: [];
};
"homepage_content": {
Row: {
"id": boolean;
"announcement": string;
"hero_eyebrow": string;
"hero_title": string;
"hero_subtitle": string;
"hero_image": string;
"hero_alt": string;
"hero_asset_id": string | null;
"hero_cta_label": string;
"hero_cta_path": string;
"hero_visible": boolean;
"story_eyebrow": string;
"story_title": string;
"story_text": string;
"story_image": string;
"story_alt": string;
"story_asset_id": string | null;
"story_visible": boolean;
"featured_visible": boolean;
"collections_visible": boolean;
"updated_at": string;
};
Insert: {
"id"?: boolean;
"announcement"?: string;
"hero_eyebrow"?: string;
"hero_title"?: string;
"hero_subtitle"?: string;
"hero_image"?: string;
"hero_alt"?: string;
"hero_asset_id"?: string | null;
"hero_cta_label"?: string;
"hero_cta_path"?: string;
"hero_visible"?: boolean;
"story_eyebrow"?: string;
"story_title"?: string;
"story_text"?: string;
"story_image"?: string;
"story_alt"?: string;
"story_asset_id"?: string | null;
"story_visible"?: boolean;
"featured_visible"?: boolean;
"collections_visible"?: boolean;
"updated_at"?: string;
};
Update: {
"id"?: boolean;
"announcement"?: string;
"hero_eyebrow"?: string;
"hero_title"?: string;
"hero_subtitle"?: string;
"hero_image"?: string;
"hero_alt"?: string;
"hero_asset_id"?: string | null;
"hero_cta_label"?: string;
"hero_cta_path"?: string;
"hero_visible"?: boolean;
"story_eyebrow"?: string;
"story_title"?: string;
"story_text"?: string;
"story_image"?: string;
"story_alt"?: string;
"story_asset_id"?: string | null;
"story_visible"?: boolean;
"featured_visible"?: boolean;
"collections_visible"?: boolean;
"updated_at"?: string;
};
Relationships: [];
};
"homepage_products": {
Row: {
"product_id": string;
"sort_order": number;
};
Insert: {
"product_id": string;
"sort_order": number;
};
Update: {
"product_id"?: string;
"sort_order"?: number;
};
Relationships: [];
};
"media_assets": {
Row: {
"id": string;
"original_name": string;
"private_path": string;
"public_path": string | null;
"public_ready": boolean;
"status": string;
"mime_type": string | null;
"byte_size": number | null;
"width": number | null;
"height": number | null;
"cleanup_pending": boolean;
"lease_until": string | null;
"created_by": string;
"created_at": string;
"lease_token": string | null;
"upload_expires_at": string | null;
};
Insert: {
"id"?: string;
"original_name": string;
"private_path": string;
"public_path"?: string | null;
"public_ready"?: boolean;
"status"?: string;
"mime_type"?: string | null;
"byte_size"?: number | null;
"width"?: number | null;
"height"?: number | null;
"cleanup_pending"?: boolean;
"lease_until"?: string | null;
"created_by"?: string;
"created_at"?: string;
"lease_token"?: string | null;
"upload_expires_at"?: string | null;
};
Update: {
"id"?: string;
"original_name"?: string;
"private_path"?: string;
"public_path"?: string | null;
"public_ready"?: boolean;
"status"?: string;
"mime_type"?: string | null;
"byte_size"?: number | null;
"width"?: number | null;
"height"?: number | null;
"cleanup_pending"?: boolean;
"lease_until"?: string | null;
"created_by"?: string;
"created_at"?: string;
"lease_token"?: string | null;
"upload_expires_at"?: string | null;
};
Relationships: [];
};
"product_collections": {
Row: {
"product_id": string;
"collection_id": string;
"sort_order": number;
};
Insert: {
"product_id": string;
"collection_id": string;
"sort_order"?: number;
};
Update: {
"product_id"?: string;
"collection_id"?: string;
"sort_order"?: number;
};
Relationships: [];
};
"product_images": {
Row: {
"id": string;
"product_id": string;
"variant_id": string | null;
"path": string;
"alt": string;
"width": number;
"height": number;
"is_primary": boolean;
"sort_order": number;
"asset_id": string | null;
};
Insert: {
"id"?: string;
"product_id": string;
"variant_id"?: string | null;
"path": string;
"alt": string;
"width": number;
"height": number;
"is_primary"?: boolean;
"sort_order"?: number;
"asset_id"?: string | null;
};
Update: {
"id"?: string;
"product_id"?: string;
"variant_id"?: string | null;
"path"?: string;
"alt"?: string;
"width"?: number;
"height"?: number;
"is_primary"?: boolean;
"sort_order"?: number;
"asset_id"?: string | null;
};
Relationships: [];
};
"product_option_values": {
Row: {
"id": string;
"option_id": string;
"product_id": string;
"key": string;
"label": string;
"colour_hex": string | null;
"image_path": string | null;
"price_delta": number;
"weight_delta_grams": number;
"active": boolean;
"sort_order": number;
"asset_id": string | null;
};
Insert: {
"id"?: string;
"option_id": string;
"product_id": string;
"key": string;
"label": string;
"colour_hex"?: string | null;
"image_path"?: string | null;
"price_delta"?: number;
"weight_delta_grams"?: number;
"active"?: boolean;
"sort_order"?: number;
"asset_id"?: string | null;
};
Update: {
"id"?: string;
"option_id"?: string;
"product_id"?: string;
"key"?: string;
"label"?: string;
"colour_hex"?: string | null;
"image_path"?: string | null;
"price_delta"?: number;
"weight_delta_grams"?: number;
"active"?: boolean;
"sort_order"?: number;
"asset_id"?: string | null;
};
Relationships: [];
};
"product_options": {
Row: {
"id": string;
"product_id": string;
"key": string;
"label": string;
"display_type": "select" | "radio" | "colour_swatch" | "image_swatch" | "checkbox" | "short_text" | "number" | "repeated_select";
"required": boolean;
"is_variant_axis": boolean;
"affects_price": boolean;
"affects_weight": boolean;
"min_selections": number;
"max_selections": number | null;
"repeat_count": number;
"allow_duplicates": boolean;
"validation_rules": Json;
"sort_order": number;
};
Insert: {
"id"?: string;
"product_id": string;
"key": string;
"label": string;
"display_type": "select" | "radio" | "colour_swatch" | "image_swatch" | "checkbox" | "short_text" | "number" | "repeated_select";
"required"?: boolean;
"is_variant_axis"?: boolean;
"affects_price"?: boolean;
"affects_weight"?: boolean;
"min_selections"?: number;
"max_selections"?: number | null;
"repeat_count"?: number;
"allow_duplicates"?: boolean;
"validation_rules"?: Json;
"sort_order"?: number;
};
Update: {
"id"?: string;
"product_id"?: string;
"key"?: string;
"label"?: string;
"display_type"?: "select" | "radio" | "colour_swatch" | "image_swatch" | "checkbox" | "short_text" | "number" | "repeated_select";
"required"?: boolean;
"is_variant_axis"?: boolean;
"affects_price"?: boolean;
"affects_weight"?: boolean;
"min_selections"?: number;
"max_selections"?: number | null;
"repeat_count"?: number;
"allow_duplicates"?: boolean;
"validation_rules"?: Json;
"sort_order"?: number;
};
Relationships: [];
};
"product_tags": {
Row: {
"product_id": string;
"tag_id": string;
};
Insert: {
"product_id": string;
"tag_id": string;
};
Update: {
"product_id"?: string;
"tag_id"?: string;
};
Relationships: [];
};
"product_variants": {
Row: {
"id": string;
"product_id": string;
"sku": string;
"title": string;
"price_override": number | null;
"price_delta": number | null;
"compare_at_price": number | null;
"weight_override_grams": number | null;
"inventory_strategy": "TRACKED" | "MADE_TO_ORDER" | "UNLIMITED" | "UNAVAILABLE";
"stock_quantity": number | null;
"active": boolean;
"sort_order": number;
};
Insert: {
"id"?: string;
"product_id": string;
"sku": string;
"title": string;
"price_override"?: number | null;
"price_delta"?: number | null;
"compare_at_price"?: number | null;
"weight_override_grams"?: number | null;
"inventory_strategy"?: "TRACKED" | "MADE_TO_ORDER" | "UNLIMITED" | "UNAVAILABLE";
"stock_quantity"?: number | null;
"active"?: boolean;
"sort_order"?: number;
};
Update: {
"id"?: string;
"product_id"?: string;
"sku"?: string;
"title"?: string;
"price_override"?: number | null;
"price_delta"?: number | null;
"compare_at_price"?: number | null;
"weight_override_grams"?: number | null;
"inventory_strategy"?: "TRACKED" | "MADE_TO_ORDER" | "UNLIMITED" | "UNAVAILABLE";
"stock_quantity"?: number | null;
"active"?: boolean;
"sort_order"?: number;
};
Relationships: [];
};
"products": {
Row: {
"id": string;
"slug": string;
"title": string;
"subtitle": string | null;
"short_description": string;
"description": string;
"materials": string;
"care": string;
"status": "draft" | "active" | "archived";
"base_price": number;
"compare_at_price": number | null;
"currency": string;
"sku": string | null;
"tax_category_key": string | null;
"inventory_strategy": "TRACKED" | "MADE_TO_ORDER" | "UNLIMITED" | "UNAVAILABLE";
"stock_quantity": number | null;
"processing_time": string | null;
"weight_grams": number | null;
"dimensions": Json;
"return_policy_class": string;
"featured": boolean;
"sort_order": number;
"seo_title": string | null;
"seo_description": string | null;
"created_at": string;
"updated_at": string;
"description_document": Json | null;
"shipping_class_key": string;
};
Insert: {
"id"?: string;
"slug": string;
"title": string;
"subtitle"?: string | null;
"short_description"?: string;
"description"?: string;
"materials"?: string;
"care"?: string;
"status"?: "draft" | "active" | "archived";
"base_price": number;
"compare_at_price"?: number | null;
"currency"?: string;
"sku"?: string | null;
"tax_category_key"?: string | null;
"inventory_strategy"?: "TRACKED" | "MADE_TO_ORDER" | "UNLIMITED" | "UNAVAILABLE";
"stock_quantity"?: number | null;
"processing_time"?: string | null;
"weight_grams"?: number | null;
"dimensions"?: Json;
"return_policy_class"?: string;
"featured"?: boolean;
"sort_order"?: number;
"seo_title"?: string | null;
"seo_description"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"description_document"?: Json | null;
"shipping_class_key"?: string;
};
Update: {
"id"?: string;
"slug"?: string;
"title"?: string;
"subtitle"?: string | null;
"short_description"?: string;
"description"?: string;
"materials"?: string;
"care"?: string;
"status"?: "draft" | "active" | "archived";
"base_price"?: number;
"compare_at_price"?: number | null;
"currency"?: string;
"sku"?: string | null;
"tax_category_key"?: string | null;
"inventory_strategy"?: "TRACKED" | "MADE_TO_ORDER" | "UNLIMITED" | "UNAVAILABLE";
"stock_quantity"?: number | null;
"processing_time"?: string | null;
"weight_grams"?: number | null;
"dimensions"?: Json;
"return_policy_class"?: string;
"featured"?: boolean;
"sort_order"?: number;
"seo_title"?: string | null;
"seo_description"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"description_document"?: Json | null;
"shipping_class_key"?: string;
};
Relationships: [];
};
"shipping_methods": {
Row: {
"id": string;
"zone_id": string;
"name": string;
"carrier": string | null;
"tracked": boolean;
"estimated_delivery": string;
"active": boolean;
"sort_order": number;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"zone_id": string;
"name": string;
"carrier"?: string | null;
"tracked"?: boolean;
"estimated_delivery"?: string;
"active"?: boolean;
"sort_order"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"zone_id"?: string;
"name"?: string;
"carrier"?: string | null;
"tracked"?: boolean;
"estimated_delivery"?: string;
"active"?: boolean;
"sort_order"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [];
};
"shipping_package_classes": {
Row: {
"key": string;
"name": string;
"active": boolean;
"updated_at": string;
};
Insert: {
"key": string;
"name": string;
"active"?: boolean;
"updated_at"?: string;
};
Update: {
"key"?: string;
"name"?: string;
"active"?: boolean;
"updated_at"?: string;
};
Relationships: [];
};
"shipping_rate_rules": {
Row: {
"id": string;
"method_id": string;
"calculation_type": "FLAT" | "BASE_PLUS_ADDITIONAL" | "PER_ITEM";
"base_amount": number;
"additional_item_amount": number;
"min_weight_grams": number;
"max_weight_grams": number | null;
"min_subtotal": number;
"max_subtotal": number | null;
"package_class_key": string | null;
"free_shipping_threshold": number | null;
"threshold_basis": "BEFORE_DISCOUNT" | "AFTER_DISCOUNT";
"price_includes_vat": boolean;
"shipping_tax_category_key": string;
"active": boolean;
"priority": number;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"method_id": string;
"calculation_type"?: "FLAT" | "BASE_PLUS_ADDITIONAL" | "PER_ITEM";
"base_amount"?: number;
"additional_item_amount"?: number;
"min_weight_grams"?: number;
"max_weight_grams"?: number | null;
"min_subtotal"?: number;
"max_subtotal"?: number | null;
"package_class_key"?: string | null;
"free_shipping_threshold"?: number | null;
"threshold_basis"?: "BEFORE_DISCOUNT" | "AFTER_DISCOUNT";
"price_includes_vat"?: boolean;
"shipping_tax_category_key"?: string;
"active"?: boolean;
"priority"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"method_id"?: string;
"calculation_type"?: "FLAT" | "BASE_PLUS_ADDITIONAL" | "PER_ITEM";
"base_amount"?: number;
"additional_item_amount"?: number;
"min_weight_grams"?: number;
"max_weight_grams"?: number | null;
"min_subtotal"?: number;
"max_subtotal"?: number | null;
"package_class_key"?: string | null;
"free_shipping_threshold"?: number | null;
"threshold_basis"?: "BEFORE_DISCOUNT" | "AFTER_DISCOUNT";
"price_includes_vat"?: boolean;
"shipping_tax_category_key"?: string;
"active"?: boolean;
"priority"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [];
};
"shipping_settings": {
Row: {
"id": boolean;
"packaging_weight_grams": number;
"updated_at": string;
};
Insert: {
"id"?: boolean;
"packaging_weight_grams"?: number;
"updated_at"?: string;
};
Update: {
"id"?: boolean;
"packaging_weight_grams"?: number;
"updated_at"?: string;
};
Relationships: [];
};
"shipping_zone_countries": {
Row: {
"country_code": string;
"zone_id": string;
};
Insert: {
"country_code": string;
"zone_id": string;
};
Update: {
"country_code"?: string;
"zone_id"?: string;
};
Relationships: [];
};
"shipping_zones": {
Row: {
"id": string;
"key": string;
"name": string;
"active": boolean;
"sort_order": number;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"key": string;
"name": string;
"active"?: boolean;
"sort_order"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"key"?: string;
"name"?: string;
"active"?: boolean;
"sort_order"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [];
};
"store_currencies": {
Row: {
"code": string;
"enabled": boolean;
"sort_order": number;
"markup_basis_points": number;
"rounding_increment_minor": number;
"updated_at": string;
};
Insert: {
"code": string;
"enabled"?: boolean;
"sort_order"?: number;
"markup_basis_points"?: number;
"rounding_increment_minor"?: number;
"updated_at"?: string;
};
Update: {
"code"?: string;
"enabled"?: boolean;
"sort_order"?: number;
"markup_basis_points"?: number;
"rounding_increment_minor"?: number;
"updated_at"?: string;
};
Relationships: [];
};
"tags": {
Row: {
"id": string;
"slug": string;
"name": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"slug": string;
"name": string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"slug"?: string;
"name"?: string;
"updated_at"?: string;
};
Relationships: [];
};
"tax_categories": {
Row: {
"key": string;
"name": string;
"active": boolean;
"updated_at": string;
};
Insert: {
"key": string;
"name": string;
"active"?: boolean;
"updated_at"?: string;
};
Update: {
"key"?: string;
"name"?: string;
"active"?: boolean;
"updated_at"?: string;
};
Relationships: [];
};
"tax_rules": {
Row: {
"id": string;
"country_code": string;
"tax_category_key": string;
"rate_basis_points": number;
"valid_from": string;
"valid_to": string | null;
"enabled": boolean;
"source": string;
"reviewed_at": string | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"country_code": string;
"tax_category_key": string;
"rate_basis_points": number;
"valid_from": string;
"valid_to"?: string | null;
"enabled"?: boolean;
"source"?: string;
"reviewed_at"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"country_code"?: string;
"tax_category_key"?: string;
"rate_basis_points"?: number;
"valid_from"?: string;
"valid_to"?: string | null;
"enabled"?: boolean;
"source"?: string;
"reviewed_at"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [];
};
"tax_settings": {
Row: {
"id": boolean;
"eu_mode": "SWEDISH_ORIGIN" | "DESTINATION";
"catalogue_prices_include_vat": boolean;
"export_rate_basis_points": number;
"export_message": string;
"reviewed_at": string | null;
"updated_at": string;
};
Insert: {
"id"?: boolean;
"eu_mode"?: "SWEDISH_ORIGIN" | "DESTINATION";
"catalogue_prices_include_vat"?: boolean;
"export_rate_basis_points"?: number;
"export_message"?: string;
"reviewed_at"?: string | null;
"updated_at"?: string;
};
Update: {
"id"?: boolean;
"eu_mode"?: "SWEDISH_ORIGIN" | "DESTINATION";
"catalogue_prices_include_vat"?: boolean;
"export_rate_basis_points"?: number;
"export_message"?: string;
"reviewed_at"?: string | null;
"updated_at"?: string;
};
Relationships: [];
};
"variant_option_values": {
Row: {
"variant_id": string;
"product_id": string;
"option_id": string;
"value_id": string;
};
Insert: {
"variant_id": string;
"product_id": string;
"option_id": string;
"value_id": string;
};
Update: {
"variant_id"?: string;
"product_id"?: string;
"option_id"?: string;
"value_id"?: string;
};
Relationships: [];
};
};
Views: {
"catalogue_products": {
Row: {
"id": string | null;
"slug": string | null;
"sort_order": number | null;
"document": Json | null;
};
Relationships: [];
};
};
Functions: {
"admin_acquire_media_lease": { Args: {"asset": string;"token": string;}; Returns: undefined};
"admin_claim_media_cleanup": { Args: {"asset": string;}; Returns: boolean};
"admin_claim_public_cleanup": { Args: {"asset": string;}; Returns: boolean};
"admin_media_references": { Args: {"asset": string;}; Returns: boolean};
"admin_mutate_tag": { Args: {"operation": string;"document": Json;"expected_updated_at"?: string;"target_id"?: string;}; Returns: undefined};
"admin_save_collection": { Args: {"document": Json;"expected_updated_at"?: string;}; Returns: Json};
"admin_save_currency_settings": { Args: {"document": Json;}; Returns: undefined};
"admin_save_discounts": { Args: {"document": Json;}; Returns: undefined};
"admin_save_homepage": { Args: {"document": Json;"product_ids": Json;"collection_ids": Json;"expected_updated_at": string;}; Returns: Json};
"admin_save_product": { Args: {"document": Json;"expected_updated_at"?: string;}; Returns: Json};
"admin_save_shipping_settings": { Args: {"document": Json;}; Returns: undefined};
"admin_save_tax_settings": { Args: {"document": Json;}; Returns: undefined};
"is_admin": { Args: Record<never, never>; Returns: boolean};
}; Enums: {
"shipping_threshold_basis": "BEFORE_DISCOUNT" | "AFTER_DISCOUNT";
"shipping_calculation_type": "FLAT" | "BASE_PLUS_ADDITIONAL" | "PER_ITEM";
"option_display_type": "select" | "radio" | "colour_swatch" | "image_swatch" | "checkbox" | "short_text" | "number" | "repeated_select";
"discount_redemption_status": "RESERVED" | "REDEEMED" | "RELEASED";
"discount_kind": "PERCENTAGE" | "FIXED_AMOUNT";
"product_status": "draft" | "active" | "archived";
"inventory_strategy": "TRACKED" | "MADE_TO_ORDER" | "UNLIMITED" | "UNAVAILABLE";
"eu_vat_mode": "SWEDISH_ORIGIN" | "DESTINATION";
}; CompositeTypes: Record<never, never>; }; };
