// Generated by npm run db:types from the checked-in migrations using PostgreSQL introspection.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = { public: {
Tables: {
"collections": {
Row: {
"id": string;
"slug": string;
"name": string;
"description": string;
"image_path": string | null;
"image_alt": string;
"active": boolean;
"sort_order": number;
"seo_title": string | null;
"seo_description": string | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"slug": string;
"name": string;
"description"?: string;
"image_path"?: string | null;
"image_alt"?: string;
"active"?: boolean;
"sort_order"?: number;
"seo_title"?: string | null;
"seo_description"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"slug"?: string;
"name"?: string;
"description"?: string;
"image_path"?: string | null;
"image_alt"?: string;
"active"?: boolean;
"sort_order"?: number;
"seo_title"?: string | null;
"seo_description"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [];
};
"product_collections": {
Row: {
"product_id": string;
"collection_id": string;
"sort_order": number;
};
Insert: {
"product_id": string;
"collection_id": string;
"sort_order"?: number;
};
Update: {
"product_id"?: string;
"collection_id"?: string;
"sort_order"?: number;
};
Relationships: [];
};
"product_images": {
Row: {
"id": string;
"product_id": string;
"variant_id": string | null;
"path": string;
"alt": string;
"width": number;
"height": number;
"is_primary": boolean;
"sort_order": number;
};
Insert: {
"id"?: string;
"product_id": string;
"variant_id"?: string | null;
"path": string;
"alt": string;
"width": number;
"height": number;
"is_primary"?: boolean;
"sort_order"?: number;
};
Update: {
"id"?: string;
"product_id"?: string;
"variant_id"?: string | null;
"path"?: string;
"alt"?: string;
"width"?: number;
"height"?: number;
"is_primary"?: boolean;
"sort_order"?: number;
};
Relationships: [];
};
"product_option_values": {
Row: {
"id": string;
"option_id": string;
"product_id": string;
"key": string;
"label": string;
"colour_hex": string | null;
"image_path": string | null;
"price_delta": number;
"weight_delta_grams": number;
"active": boolean;
"sort_order": number;
};
Insert: {
"id"?: string;
"option_id": string;
"product_id": string;
"key": string;
"label": string;
"colour_hex"?: string | null;
"image_path"?: string | null;
"price_delta"?: number;
"weight_delta_grams"?: number;
"active"?: boolean;
"sort_order"?: number;
};
Update: {
"id"?: string;
"option_id"?: string;
"product_id"?: string;
"key"?: string;
"label"?: string;
"colour_hex"?: string | null;
"image_path"?: string | null;
"price_delta"?: number;
"weight_delta_grams"?: number;
"active"?: boolean;
"sort_order"?: number;
};
Relationships: [];
};
"product_options": {
Row: {
"id": string;
"product_id": string;
"key": string;
"label": string;
"display_type": "select" | "radio" | "colour_swatch" | "image_swatch" | "checkbox" | "short_text" | "number" | "repeated_select";
"required": boolean;
"is_variant_axis": boolean;
"affects_price": boolean;
"affects_weight": boolean;
"min_selections": number;
"max_selections": number | null;
"repeat_count": number;
"allow_duplicates": boolean;
"validation_rules": Json;
"sort_order": number;
};
Insert: {
"id"?: string;
"product_id": string;
"key": string;
"label": string;
"display_type": "select" | "radio" | "colour_swatch" | "image_swatch" | "checkbox" | "short_text" | "number" | "repeated_select";
"required"?: boolean;
"is_variant_axis"?: boolean;
"affects_price"?: boolean;
"affects_weight"?: boolean;
"min_selections"?: number;
"max_selections"?: number | null;
"repeat_count"?: number;
"allow_duplicates"?: boolean;
"validation_rules"?: Json;
"sort_order"?: number;
};
Update: {
"id"?: string;
"product_id"?: string;
"key"?: string;
"label"?: string;
"display_type"?: "select" | "radio" | "colour_swatch" | "image_swatch" | "checkbox" | "short_text" | "number" | "repeated_select";
"required"?: boolean;
"is_variant_axis"?: boolean;
"affects_price"?: boolean;
"affects_weight"?: boolean;
"min_selections"?: number;
"max_selections"?: number | null;
"repeat_count"?: number;
"allow_duplicates"?: boolean;
"validation_rules"?: Json;
"sort_order"?: number;
};
Relationships: [];
};
"product_tags": {
Row: {
"product_id": string;
"tag_id": string;
};
Insert: {
"product_id": string;
"tag_id": string;
};
Update: {
"product_id"?: string;
"tag_id"?: string;
};
Relationships: [];
};
"product_variants": {
Row: {
"id": string;
"product_id": string;
"sku": string;
"title": string;
"price_override": number | null;
"price_delta": number | null;
"compare_at_price": number | null;
"weight_override_grams": number | null;
"inventory_strategy": "TRACKED" | "MADE_TO_ORDER" | "UNLIMITED" | "UNAVAILABLE";
"stock_quantity": number | null;
"active": boolean;
"sort_order": number;
};
Insert: {
"id"?: string;
"product_id": string;
"sku": string;
"title": string;
"price_override"?: number | null;
"price_delta"?: number | null;
"compare_at_price"?: number | null;
"weight_override_grams"?: number | null;
"inventory_strategy"?: "TRACKED" | "MADE_TO_ORDER" | "UNLIMITED" | "UNAVAILABLE";
"stock_quantity"?: number | null;
"active"?: boolean;
"sort_order"?: number;
};
Update: {
"id"?: string;
"product_id"?: string;
"sku"?: string;
"title"?: string;
"price_override"?: number | null;
"price_delta"?: number | null;
"compare_at_price"?: number | null;
"weight_override_grams"?: number | null;
"inventory_strategy"?: "TRACKED" | "MADE_TO_ORDER" | "UNLIMITED" | "UNAVAILABLE";
"stock_quantity"?: number | null;
"active"?: boolean;
"sort_order"?: number;
};
Relationships: [];
};
"products": {
Row: {
"id": string;
"slug": string;
"title": string;
"subtitle": string | null;
"short_description": string;
"description": string;
"materials": string;
"care": string;
"status": "draft" | "active" | "archived";
"base_price": number;
"compare_at_price": number | null;
"currency": string;
"sku": string | null;
"tax_category_key": string | null;
"inventory_strategy": "TRACKED" | "MADE_TO_ORDER" | "UNLIMITED" | "UNAVAILABLE";
"stock_quantity": number | null;
"processing_time": string | null;
"weight_grams": number | null;
"dimensions": Json;
"return_policy_class": string;
"featured": boolean;
"sort_order": number;
"seo_title": string | null;
"seo_description": string | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"slug": string;
"title": string;
"subtitle"?: string | null;
"short_description"?: string;
"description"?: string;
"materials"?: string;
"care"?: string;
"status"?: "draft" | "active" | "archived";
"base_price": number;
"compare_at_price"?: number | null;
"currency"?: string;
"sku"?: string | null;
"tax_category_key"?: string | null;
"inventory_strategy"?: "TRACKED" | "MADE_TO_ORDER" | "UNLIMITED" | "UNAVAILABLE";
"stock_quantity"?: number | null;
"processing_time"?: string | null;
"weight_grams"?: number | null;
"dimensions"?: Json;
"return_policy_class"?: string;
"featured"?: boolean;
"sort_order"?: number;
"seo_title"?: string | null;
"seo_description"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"slug"?: string;
"title"?: string;
"subtitle"?: string | null;
"short_description"?: string;
"description"?: string;
"materials"?: string;
"care"?: string;
"status"?: "draft" | "active" | "archived";
"base_price"?: number;
"compare_at_price"?: number | null;
"currency"?: string;
"sku"?: string | null;
"tax_category_key"?: string | null;
"inventory_strategy"?: "TRACKED" | "MADE_TO_ORDER" | "UNLIMITED" | "UNAVAILABLE";
"stock_quantity"?: number | null;
"processing_time"?: string | null;
"weight_grams"?: number | null;
"dimensions"?: Json;
"return_policy_class"?: string;
"featured"?: boolean;
"sort_order"?: number;
"seo_title"?: string | null;
"seo_description"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [];
};
"tags": {
Row: {
"id": string;
"slug": string;
"name": string;
};
Insert: {
"id"?: string;
"slug": string;
"name": string;
};
Update: {
"id"?: string;
"slug"?: string;
"name"?: string;
};
Relationships: [];
};
"variant_option_values": {
Row: {
"variant_id": string;
"product_id": string;
"option_id": string;
"value_id": string;
};
Insert: {
"variant_id": string;
"product_id": string;
"option_id": string;
"value_id": string;
};
Update: {
"variant_id"?: string;
"product_id"?: string;
"option_id"?: string;
"value_id"?: string;
};
Relationships: [];
};
};
Views: {
"catalogue_products": {
Row: {
"id": string | null;
"slug": string | null;
"sort_order": number | null;
"document": Json | null;
};
Relationships: [];
};
};
Functions: Record<never, never>; Enums: {
"inventory_strategy": "TRACKED" | "MADE_TO_ORDER" | "UNLIMITED" | "UNAVAILABLE";
"product_status": "draft" | "active" | "archived";
"option_display_type": "select" | "radio" | "colour_swatch" | "image_swatch" | "checkbox" | "short_text" | "number" | "repeated_select";
}; CompositeTypes: Record<never, never>; }; };
