import { z } from "zod";
const text = z.string().max(10000);
export const homepageSchema = z.object({
  id: z.literal(true),
  announcement: text,
  announcement_sv: text.nullable().default(null),
  hero_eyebrow: text,
  hero_eyebrow_sv: text.nullable().default(null),
  hero_title: text,
  hero_title_sv: text.nullable().default(null),
  hero_subtitle: text,
  hero_subtitle_sv: text.nullable().default(null),
  hero_image: text,
  hero_alt: text,
  hero_alt_sv: text.nullable().default(null),
  hero_asset_id: z.uuid().nullable(),
  hero_cta_label: text,
  hero_cta_label_sv: text.nullable().default(null),
  hero_cta_path: z
    .string()
    .regex(/^\/(?!\/)[^\\\s]*$/, "Use a local path such as /shop."),
  hero_visible: z.boolean(),
  story_eyebrow: text,
  story_eyebrow_sv: text.nullable().default(null),
  story_title: text,
  story_title_sv: text.nullable().default(null),
  story_text: text,
  story_text_sv: text.nullable().default(null),
  story_image: text,
  story_alt: text,
  story_alt_sv: text.nullable().default(null),
  story_asset_id: z.uuid().nullable(),
  story_visible: z.boolean(),
  featured_visible: z.boolean(),
  collections_visible: z.boolean(),
  updated_at: z.string(),
  product_ids: z.array(z.uuid()).max(50),
  collection_ids: z.array(z.uuid()).max(50),
});
export type Homepage = z.infer<typeof homepageSchema>;
export const homepageDefaults: Homepage = {
  id: true,
  announcement: "A little handmade warmth, from Sweden to your home",
  announcement_sv: "Lite handgjord värme, från Sverige till ditt hem",
  hero_eyebrow: "Sculptural shapes. Everyday softness.",
  hero_eyebrow_sv: "Skulpturala former. Mjukhet för varje dag.",
  hero_title: "A softer kind of home.",
  hero_title_sv: "Ett mjukare slags hem.",
  hero_subtitle:
    "Thoughtfully knotted pillows and little things to love. Made by hand, to make a space your own.",
  hero_subtitle_sv:
    "Omsorgsfullt knutna kuddar och små detaljer att tycka om. Handgjorda för att göra ditt rum personligt.",
  hero_image: "/images/catalogue/story.jpg",
  hero_alt: "Sculptural ivory knot pillow beside a ceramic vase",
  hero_alt_sv: "Skulptural elfenbensvit knutkudde bredvid en keramikvas",
  hero_asset_id: null,
  hero_cta_label: "Discover the collection",
  hero_cta_label_sv: "Upptäck kollektionen",
  hero_cta_path: "/shop",
  hero_visible: true,
  story_eyebrow: "From our hands to your home",
  story_eyebrow_sv: "Från våra händer till ditt hem",
  story_title: "Made slowly. Loved for longer.",
  story_title_sv: "Tillverkad långsamt. Älskad längre.",
  story_text:
    "We believe the things around us should have a little soul. A beautiful texture. An unexpected shape. The quiet character of something made by hand.\n\nMacmaer brings together Scandinavian simplicity and a love of making — one knot at a time.",
  story_text_sv:
    "Vi tror att sakerna omkring oss ska ha lite själ. En vacker struktur. En oväntad form. Den stillsamma karaktären hos något som är gjort för hand.\n\nMacmaer förenar skandinavisk enkelhet med skaparglädje – en knut i taget.",
  story_image: "/images/catalogue/cotton.jpg",
  story_alt: "A handmade ivory knot pillow held close",
  story_alt_sv: "En handgjord elfenbensvit knutkudde som hålls nära",
  story_asset_id: null,
  story_visible: true,
  featured_visible: true,
  collections_visible: true,
  updated_at: "",
  product_ids: [],
  collection_ids: [],
};
